// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSAhz9ArP6X3W6UwV9dDyxeisYQuIL_V4',
    appId: '1:696349734381:web:dafe17692c663eb54f23e4',
    messagingSenderId: '696349734381',
    projectId: 'expensetracker-a5c10',
    authDomain: 'expensetracker-a5c10.firebaseapp.com',
    storageBucket: 'expensetracker-a5c10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfeugZmdrys-N9qKVDULFLOr_mGrfFnpw',
    appId: '1:696349734381:android:30942846234835bb4f23e4',
    messagingSenderId: '696349734381',
    projectId: 'expensetracker-a5c10',
    storageBucket: 'expensetracker-a5c10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeZ4AxeWyuSDgllG8X5HWNYHkvyhjzS54',
    appId: '1:696349734381:ios:7d763fdd613ff3004f23e4',
    messagingSenderId: '696349734381',
    projectId: 'expensetracker-a5c10',
    storageBucket: 'expensetracker-a5c10.firebasestorage.app',
    iosBundleId: 'com.example.espense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeZ4AxeWyuSDgllG8X5HWNYHkvyhjzS54',
    appId: '1:696349734381:ios:7d763fdd613ff3004f23e4',
    messagingSenderId: '696349734381',
    projectId: 'expensetracker-a5c10',
    storageBucket: 'expensetracker-a5c10.firebasestorage.app',
    iosBundleId: 'com.example.espense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSAhz9ArP6X3W6UwV9dDyxeisYQuIL_V4',
    appId: '1:696349734381:web:67a702352a11a1874f23e4',
    messagingSenderId: '696349734381',
    projectId: 'expensetracker-a5c10',
    authDomain: 'expensetracker-a5c10.firebaseapp.com',
    storageBucket: 'expensetracker-a5c10.firebasestorage.app',
  );

}